[package]
name = "rust-challenges"
version = "0.1.0"
authors = ["Teddy Byron <ted@tedbyron.com>"]
license = "MIT"
edition = "2018"

[dependencies]
chrono = "0"
itertools = "0"
lazy_static = "1"
regex = "1"
unicode-segmentation = "1"
